apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-config
  namespace: 74cudwfj-parameters-dev
data:
  ENV_VAR1: value1
  # Multi-line string for application-specific configuration, often used in file-based properties.
  application.properties: |
    server.port=8080
    logging.level.root=INFO
