apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
  namespace: 74cudwfj-parameters-dev
# Stores key-value pairs as plain strings that will be base64-encoded automatically.
stringData:
  ENV_VAR4: value4
  # Multi-line string for storing application-specific configurations.
  application.secret.properties: |
    server.port=8080
    logging.level.root=INFO
